export interface CountryState {
  code: string
  name: string
  cities?: string[]
}

export interface Country {
  code: string
  name: string
  states: CountryState[]
}

export const countries: Country[] = [
  {
    code: 'US',
    name: 'United States',
    states: [
      { code: 'AL', name: 'Alabama', cities: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa', 'Hoover', 'Dothan', 'Decatur', 'Auburn', 'Madison', 'Florence', 'Gadsden', 'Vestavia Hills', 'Prattville', 'Phenix City', 'Alabaster', 'Bessemer', 'Enterprise', 'Opelika', 'Homewood'] },
      { code: 'AK', name: 'Alaska', cities: ['Anchorage', 'Juneau', 'Fairbanks', 'Sitka', 'Ketchikan', 'Wasilla', 'Kenai', 'Kodiak', 'Bethel', 'Palmer', 'Homer', 'Barrow', 'Soldotna', 'Nome', 'Valdez', 'Seward', 'Kotzebue', 'Wrangell', 'Petersburg', 'Craig'] },
      { code: 'AZ', name: 'Arizona', cities: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale', 'Gilbert', 'Tempe', 'Peoria', 'Surprise', 'Yuma', 'Avondale', 'Goodyear', 'Flagstaff', 'Buckeye', 'Lake Havasu City', 'Casa Grande', 'Sierra Vista', 'Maricopa', 'Oro Valley', 'Prescott', 'Bullhead City', 'Prescott Valley', 'Apache Junction', 'Marana'] },
      { code: 'AR', name: 'Arkansas', cities: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro', 'North Little Rock', 'Conway', 'Rogers', 'Pine Bluff', 'Bentonville', 'Hot Springs', 'Benton', 'Texarkana', 'Sherwood', 'Jacksonville', 'Russellville', 'Bella Vista', 'West Memphis', 'Paragould', 'Cabot', 'Searcy', 'Van Buren', 'El Dorado', 'Blytheville', 'Harrison'] },
      { code: 'CA', name: 'California', cities: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana', 'Riverside', 'Stockton', 'Irvine', 'Chula Vista', 'Fremont', 'San Bernardino', 'Modesto', 'Fontana', 'Oxnard', 'Moreno Valley', 'Huntington Beach', 'Glendale', 'Santa Clarita', 'Garden Grove', 'Oceanside', 'Rancho Cucamonga', 'Santa Rosa', 'Ontario', 'Lancaster', 'Elk Grove', 'Corona', 'Palmdale', 'Salinas', 'Pomona', 'Hayward', 'Escondido', 'Torrance', 'Sunnyvale', 'Orange', 'Fullerton', 'Pasadena', 'Thousand Oaks', 'Visalia', 'Simi Valley', 'Concord', 'Roseville'] },
      { code: 'CO', name: 'Colorado', cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Thornton', 'Arvada', 'Westminster', 'Pueblo', 'Centennial', 'Boulder', 'Greeley', 'Longmont', 'Loveland', 'Grand Junction', 'Broomfield', 'Castle Rock', 'Commerce City', 'Parker', 'Littleton', 'Northglenn', 'Brighton', 'Englewood', 'Wheat Ridge', 'Lafayette'] },
      { code: 'CT', name: 'Connecticut', cities: ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury', 'Norwalk', 'Danbury', 'New Britain', 'West Hartford', 'Greenwich', 'Hamden', 'Meriden', 'Bristol', 'Manchester', 'West Haven', 'Milford', 'Stratford', 'East Hartford', 'Middletown', 'Wallingford', 'Norwich', 'Shelton', 'Torrington', 'Trumbull', 'Glastonbury'] },
      { code: 'DE', name: 'Delaware', cities: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna', 'Milford', 'Seaford', 'Georgetown', 'Elsmere', 'New Castle', 'Bear', 'Brookside', 'Pike Creek', 'Hockessin', 'Glasgow', 'Claymont', 'Edgemoor', 'North Star', 'Pike Creek Valley', 'Brandywine'] },
      { code: 'FL', name: 'Florida', cities: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Tallahassee', 'Fort Lauderdale', 'Port St. Lucie', 'Cape Coral', 'Pembroke Pines', 'Hollywood', 'Miramar', 'Gainesville', 'Coral Springs', 'Miami Gardens', 'Clearwater', 'Palm Bay', 'West Palm Beach', 'Pompano Beach', 'Lakeland', 'Davie', 'Miami Beach', 'Sunrise', 'Plantation', 'Boca Raton', 'Deltona', 'Largo', 'Deerfield Beach', 'Boynton Beach', 'Melbourne', 'Lauderhill', 'Weston', 'Kissimmee', 'Homestead', 'Delray Beach', 'Ocala', 'Sarasota', 'Pensacola', 'Fort Myers'] },
      { code: 'GA', name: 'Georgia', cities: ['Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah', 'Athens', 'Sandy Springs', 'Roswell', 'Albany', 'Johns Creek', 'Warner Robins', 'Alpharetta', 'Marietta', 'Valdosta', 'Smyrna', 'Dunwoody', 'Rome', 'East Point', 'Peachtree Corners', 'Gainesville', 'Hinesville', 'Kennesaw', 'Newnan', 'Douglasville', 'Lawrenceville', 'Duluth', 'Woodstock', 'Stockbridge', 'Decatur', 'Carrollton'] },
      { code: 'HI', name: 'Hawaii', cities: ['Honolulu', 'Pearl City', 'Hilo', 'Kailua', 'Waipahu', 'Kaneohe', 'Mililani Town', 'Kahului', 'Ewa Gentry', 'Mililani Mauka', 'Kihei', 'Wahiawa', 'Ewa Beach', 'Royal Kunia', 'Aiea', 'Makakilo', 'Wailuku', 'Halawa', 'Schofield Barracks', 'Waianae'] },
      { code: 'ID', name: 'Idaho', cities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello', 'Caldwell', 'Coeur d\'Alene', 'Twin Falls', 'Lewiston', 'Post Falls', 'Rexburg', 'Moscow', 'Eagle', 'Kuna', 'Ammon', 'Chubbuck', 'Hayden', 'Mountain Home', 'Jerome', 'Blackfoot', 'Garden City', 'Burley', 'Rathdrum', 'Payette', 'Sandpoint'] },
      { code: 'IL', name: 'Illinois', cities: ['Chicago', 'Aurora', 'Rockford', 'Joliet', 'Naperville', 'Springfield', 'Peoria', 'Elgin', 'Waukegan', 'Cicero', 'Champaign', 'Bloomington', 'Arlington Heights', 'Evanston', 'Decatur', 'Schaumburg', 'Bolingbrook', 'Palatine', 'Skokie', 'Des Plaines', 'Orland Park', 'Tinley Park', 'Oak Lawn', 'Berwyn', 'Mount Prospect', 'Normal', 'Wheaton', 'Hoffman Estates', 'Oak Park', 'Downers Grove'] },
      { code: 'IN', name: 'Indiana', cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel', 'Fishers', 'Bloomington', 'Hammond', 'Gary', 'Muncie', 'Lafayette', 'Terre Haute', 'Kokomo', 'Anderson', 'Noblesville', 'Greenwood', 'Elkhart', 'Mishawaka', 'Lawrence', 'Jeffersonville', 'Columbus', 'Portage', 'New Albany', 'Richmond', 'Westfield', 'Valparaiso', 'Goshen', 'Michigan City', 'Marion', 'East Chicago'] },
      { code: 'IA', name: 'Iowa', cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City', 'Waterloo', 'Council Bluffs', 'Ames', 'West Des Moines', 'Dubuque', 'Ankeny', 'Urbandale', 'Cedar Falls', 'Marion', 'Bettendorf', 'Mason City', 'Marshalltown', 'Clinton', 'Burlington', 'Ottumwa', 'Fort Dodge', 'Muscatine', 'Coralville', 'Johnston', 'North Liberty'] },
      { code: 'KS', name: 'Kansas', cities: ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka', 'Lawrence', 'Shawnee', 'Manhattan', 'Lenexa', 'Salina', 'Hutchinson', 'Leavenworth', 'Leawood', 'Dodge City', 'Garden City', 'Emporia', 'Junction City', 'Derby', 'Prairie Village', 'Hays', 'Liberal', 'Gladstone', 'Pittsburg', 'Newton', 'Great Bend'] },
      { code: 'KY', name: 'Kentucky', cities: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington', 'Hopkinsville', 'Richmond', 'Florence', 'Georgetown', 'Henderson', 'Elizabethtown', 'Nicholasville', 'Jeffersontown', 'Frankfort', 'Paducah', 'Radcliff', 'Ashland', 'Murray', 'Erlanger', 'Winchester', 'Madisonville', 'St. Matthews', 'Fort Thomas', 'Danville', 'Independence'] },
      { code: 'LA', name: 'Louisiana', cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles', 'Kenner', 'Bossier City', 'Monroe', 'Alexandria', 'Houma', 'Marrero', 'New Iberia', 'Laplace', 'Slidell', 'Prairieville', 'Central', 'Ruston', 'Sulphur', 'Hammond', 'Natchitoches', 'Gretna', 'Opelousas', 'Pineville', 'Baker', 'Zachary'] },
      { code: 'ME', name: 'Maine', cities: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn', 'Biddeford', 'Sanford', 'Saco', 'Augusta', 'Westbrook', 'Waterville', 'Presque Isle', 'Orono', 'York', 'Windham', 'Gorham', 'Brunswick', 'Scarborough', 'Caribou', 'Old Town', 'Ellsworth', 'Belfast', 'Calais', 'Rockland', 'Gardiner'] },
      { code: 'MD', name: 'Maryland', cities: ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg', 'Bowie', 'Hagerstown', 'Annapolis', 'College Park', 'Salisbury', 'Laurel', 'Greenbelt', 'Cumberland', 'Westminster', 'Hyattsville', 'Takoma Park', 'Easton', 'Elkton', 'Aberdeen', 'Havre de Grace', 'Cambridge', 'La Plata', 'Ocean City', 'Severn', 'Glen Burnie', 'Germantown'] },
      { code: 'MA', name: 'Massachusetts', cities: ['Boston', 'Worcester', 'Springfield', 'Lowell', 'Cambridge', 'New Bedford', 'Brockton', 'Quincy', 'Lynn', 'Fall River', 'Newton', 'Lawrence', 'Somerville', 'Framingham', 'Haverhill', 'Waltham', 'Malden', 'Brookline', 'Plymouth', 'Medford', 'Taunton', 'Chicopee', 'Weymouth', 'Revere', 'Peabody', 'Methuen', 'Barnstable', 'Pittsfield', 'Attleboro', 'Everett'] },
      { code: 'MI', name: 'Michigan', cities: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Lansing', 'Ann Arbor', 'Flint', 'Dearborn', 'Livonia', 'Westland', 'Troy', 'Farmington Hills', 'Kalamazoo', 'Wyoming', 'Southfield', 'Rochester Hills', 'Taylor', 'Pontiac', 'St. Clair Shores', 'Royal Oak', 'Novi', 'Dearborn Heights', 'Battle Creek', 'Saginaw', 'Kentwood', 'East Lansing', 'Roseville', 'Portage', 'Midland', 'Lincoln Park'] },
      { code: 'MN', name: 'Minnesota', cities: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington', 'Brooklyn Park', 'Plymouth', 'St. Cloud', 'Eagan', 'Woodbury', 'Maple Grove', 'Eden Prairie', 'Coon Rapids', 'Burnsville', 'Blaine', 'Lakeville', 'Minnetonka', 'Apple Valley', 'Edina', 'St. Louis Park', 'Moorhead', 'Mankato', 'Shakopee', 'Cottage Grove', 'Richfield', 'Roseville', 'Inver Grove Heights', 'Andover', 'Brooklyn Center', 'Savage'] },
      { code: 'MS', name: 'Mississippi', cities: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi', 'Meridian', 'Tupelo', 'Greenville', 'Olive Branch', 'Horn Lake', 'Clinton', 'Pearl', 'Ridgeland', 'Starkville', 'Columbus', 'Vicksburg', 'Pascagoula', 'Ocean Springs', 'Madison', 'Flowood', 'Clarksdale', 'Greenwood', 'Laurel', 'Natchez', 'McComb'] },
      { code: 'MO', name: 'Missouri', cities: ['Kansas City', 'St. Louis', 'Springfield', 'Independence', 'Columbia', 'Lee\'s Summit', 'O\'Fallon', 'St. Joseph', 'St. Charles', 'St. Peters', 'Blue Springs', 'Florissant', 'Joplin', 'Chesterfield', 'Jefferson City', 'Cape Girardeau', 'Oakville', 'Wildwood', 'University City', 'Ballwin', 'Raytown', 'Liberty', 'Wentzville', 'Mehlville', 'Kirkwood'] },
      { code: 'MT', name: 'Montana', cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte', 'Helena', 'Kalispell', 'Havre', 'Anaconda', 'Miles City', 'Belgrade', 'Livingston', 'Laurel', 'Whitefish', 'Lewistown', 'Sidney', 'Glendive', 'Hamilton', 'Columbia Falls', 'Polson', 'Dillon', 'Hardin', 'Browning', 'Deer Lodge', 'Red Lodge'] },
      { code: 'NE', name: 'Nebraska', cities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney', 'Fremont', 'Hastings', 'North Platte', 'Norfolk', 'Columbus', 'Papillion', 'La Vista', 'Scottsbluff', 'South Sioux City', 'Beatrice', 'Lexington', 'Gering', 'Alliance', 'York', 'McCook', 'Nebraska City', 'Seward', 'Sidney', 'Chadron', 'Wayne'] },
      { code: 'NV', name: 'Nevada', cities: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks', 'Carson City', 'Fernley', 'Elko', 'Mesquite', 'Boulder City', 'Fallon', 'Winnemucca', 'West Wendover', 'Ely', 'Yerington', 'Carlin', 'Lovelock', 'Wells', 'Caliente', 'Gabbs'] },
      { code: 'NH', name: 'New Hampshire', cities: ['Manchester', 'Nashua', 'Concord', 'Derry', 'Rochester', 'Salem', 'Dover', 'Merrimack', 'Londonderry', 'Hudson', 'Keene', 'Bedford', 'Portsmouth', 'Milford', 'Goffstown', 'Laconia', 'Hampton', 'Durham', 'Exeter', 'Windham', 'Hooksett', 'Claremont', 'Lebanon', 'Pelham', 'Amherst'] },
      { code: 'NJ', name: 'New Jersey', cities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison', 'Woodbridge', 'Lakewood', 'Toms River', 'Hamilton', 'Trenton', 'Clifton', 'Camden', 'Brick', 'East Orange', 'Bayonne', 'Lynn', 'Passaic', 'Union City', 'Irvington', 'Wayne', 'Hoboken', 'West New York', 'Bloomfield', 'Hackensack', 'Atlantic City', 'Kearny', 'Vineland', 'Sayreville', 'New Brunswick', 'Plainfield'] },
      { code: 'NM', name: 'New Mexico', cities: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell', 'Farmington', 'Clovis', 'Hobbs', 'Alamogordo', 'Carlsbad', 'Gallup', 'Deming', 'Los Alamos', 'Chaparral', 'Sunland Park', 'Las Vegas', 'Portales', 'Silver City', 'North Valley', 'Artesia', 'Grants', 'Shiprock', 'Española', 'Raton', 'Truth or Consequences'] },
      { code: 'NY', name: 'New York', cities: ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany', 'New Rochelle', 'Mount Vernon', 'Schenectady', 'Utica', 'White Plains', 'Hempstead', 'Troy', 'Niagara Falls', 'Binghamton', 'Freeport', 'Valley Stream', 'Long Beach', 'Rome', 'Watertown', 'Ithaca', 'Middletown', 'Spring Valley', 'Elmira', 'Jamestown', 'Poughkeepsie', 'Newburgh', 'Tonawanda', 'West Seneca', 'Cheektowaga'] },
      { code: 'NC', name: 'North Carolina', cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem', 'Fayetteville', 'Cary', 'Wilmington', 'High Point', 'Greenville', 'Asheville', 'Concord', 'Gastonia', 'Jacksonville', 'Chapel Hill', 'Rocky Mount', 'Burlington', 'Wilson', 'Huntersville', 'Kannapolis', 'Apex', 'Hickory', 'Goldsboro', 'Indian Trail', 'Mooresville', 'Monroe', 'Salisbury', 'New Bern', 'Sanford', 'Matthews'] },
      { code: 'ND', name: 'North Dakota', cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo', 'Williston', 'Dickinson', 'Mandan', 'Jamestown', 'Wahpeton', 'Devils Lake', 'Valley City', 'Grafton', 'Rugby', 'Beulah', 'Watford City', 'New Town', 'Carrington', 'Hazelton', 'Horace'] },
      { code: 'OH', name: 'Ohio', cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton', 'Parma', 'Canton', 'Youngstown', 'Lorain', 'Hamilton', 'Springfield', 'Kettering', 'Elyria', 'Lakewood', 'Cuyahoga Falls', 'Middletown', 'Euclid', 'Newark', 'Mansfield', 'Mentor', 'Beavercreek', 'Cleveland Heights', 'Strongsville', 'Fairborn', 'Dublin', 'Warren', 'Findlay', 'Lancaster', 'Lima'] },
      { code: 'OK', name: 'Oklahoma', cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Lawton', 'Edmond', 'Moore', 'Midwest City', 'Enid', 'Stillwater', 'Muskogee', 'Bartlesville', 'Owasso', 'Shawnee', 'Ponca City', 'Ardmore', 'Duncan', 'Bixby', 'McAlester', 'Jenks', 'Yukon', 'Bethany', 'Mustang', 'Sand Springs', 'Claremore'] },
      { code: 'OR', name: 'Oregon', cities: ['Portland', 'Eugene', 'Salem', 'Gresham', 'Hillsboro', 'Bend', 'Beaverton', 'Medford', 'Springfield', 'Corvallis', 'Albany', 'Tigard', 'Lake Oswego', 'Keizer', 'Grants Pass', 'Oregon City', 'McMinnville', 'Redmond', 'Tualatin', 'West Linn', 'Woodburn', 'Forest Grove', 'Newberg', 'Roseburg', 'Klamath Falls', 'Ashland', 'Milwaukie', 'Happy Valley', 'Central Point', 'Canby'] },
      { code: 'PA', name: 'Pennsylvania', cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading', 'Scranton', 'Bethlehem', 'Lancaster', 'Harrisburg', 'Altoona', 'York', 'State College', 'Wilkes-Barre', 'Chester', 'Williamsport', 'Easton', 'Lebanon', 'Hazleton', 'New Castle', 'Johnstown', 'Washington', 'West Chester', 'Butler', 'Norristown', 'Pottstown', 'Carbondale', 'Chambersburg', 'Greensburg', 'Indiana', 'McKeesport'] },
      { code: 'RI', name: 'Rhode Island', cities: ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence', 'Woonsocket', 'Newport', 'Central Falls', 'Westerly', 'North Providence', 'West Warwick', 'Johnston', 'North Kingstown', 'South Kingstown', 'Coventry', 'Cumberland', 'Lincoln', 'Smithfield', 'Barrington', 'Bristol', 'Middletown', 'Tiverton', 'East Greenwich', 'North Smithfield', 'Narragansett'] },
      { code: 'SC', name: 'South Carolina', cities: ['Charleston', 'Columbia', 'North Charleston', 'Mount Pleasant', 'Rock Hill', 'Greenville', 'Summerville', 'Sumter', 'Goose Creek', 'Hilton Head Island', 'Florence', 'Spartanburg', 'Anderson', 'Greer', 'Myrtle Beach', 'Aiken', 'Greenwood', 'North Augusta', 'Mauldin', 'Easley', 'Simpsonville', 'Orangeburg', 'Hanahan', 'Lexington', 'Conway'] },
      { code: 'SD', name: 'South Dakota', cities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown', 'Mitchell', 'Yankton', 'Pierre', 'Huron', 'Spearfish', 'Vermillion', 'Brandon', 'Box Elder', 'Sturgis', 'Madison', 'Hot Springs', 'Lead', 'Deadwood', 'Winner', 'Milbank', 'Mobridge', 'Sisseton', 'Wagner', 'Eagle Butte', 'Belle Fourche'] },
      { code: 'TN', name: 'Tennessee', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville', 'Murfreesboro', 'Franklin', 'Jackson', 'Johnson City', 'Bartlett', 'Hendersonville', 'Kingsport', 'Collierville', 'Cleveland', 'Smyrna', 'Germantown', 'Brentwood', 'Columbia', 'La Vergne', 'Gallatin', 'Cookeville', 'Mount Juliet', 'Lebanon', 'Morristown', 'Oak Ridge', 'Maryville', 'Bristol', 'Shelbyville', 'Dyersburg', 'East Ridge'] },
      { code: 'TX', name: 'Texas', cities: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Lubbock', 'Laredo', 'Garland', 'Irving', 'Amarillo', 'Grand Prairie', 'Brownsville', 'McKinney', 'Frisco', 'Pasadena', 'Killeen', 'Mesquite', 'McAllen', 'Carrollton', 'Midland', 'Denton', 'Pearland', 'Lewisville', 'Richardson', 'College Station', 'Beaumont', 'Odessa', 'Waco', 'Round Rock', 'Tyler', 'Sugar Land', 'Allen', 'League City', 'Longview', 'Abilene', 'San Angelo', 'Wichita Falls', 'Baytown', 'Missouri City', 'Temple', 'Flower Mound', 'New Braunfels', 'Cedar Park', 'Pharr', 'Conroe'] },
      { code: 'UT', name: 'Utah', cities: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem', 'Sandy', 'Ogden', 'St. George', 'Layton', 'Taylorsville', 'South Jordan', 'Lehi', 'Logan', 'Murray', 'Draper', 'Bountiful', 'Riverton', 'Roy', 'Pleasant Grove', 'Tooele', 'Cottonwood Heights', 'Midvale', 'Spanish Fork', 'Springville', 'Eagle Mountain', 'Payson', 'Herriman', 'American Fork', 'Cedar City', 'Clearfield'] },
      { code: 'VT', name: 'Vermont', cities: ['Burlington', 'Essex', 'South Burlington', 'Colchester', 'Rutland', 'Bennington', 'Brattleboro', 'Milton', 'Hartford', 'Williston', 'Middlebury', 'Barre', 'Montpelier', 'St. Albans', 'Winooski', 'Shelburne', 'St. Johnsbury', 'Swanton', 'Northfield', 'Springfield', 'Vergennes', 'Bellows Falls', 'Manchester', 'White River Junction', 'Newport'] },
      { code: 'VA', name: 'Virginia', cities: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News', 'Alexandria', 'Hampton', 'Portsmouth', 'Suffolk', 'Roanoke', 'Lynchburg', 'Harrisonburg', 'Leesburg', 'Charlottesville', 'Danville', 'Blacksburg', 'Manassas', 'Petersburg', 'Frederick', 'Hopewell', 'Winchester', 'Radford', 'Waynesboro', 'Colonial Heights', 'Bristol'] },
      { code: 'WA', name: 'Washington', cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Kent', 'Everett', 'Renton', 'Yakima', 'Federal Way', 'Spokane Valley', 'Bellingham', 'Kennewick', 'Auburn', 'Pasco', 'Marysville', 'Lakewood', 'Redmond', 'Shoreline', 'Richland', 'Kirkland', 'Burien', 'Sammamish', 'Olympia', 'Lacey', 'Edmonds', 'Bremerton', 'Puyallup', 'Bothell', 'Lynnwood'] },
      { code: 'WV', name: 'West Virginia', cities: ['Charleston', 'Huntington', 'Parkersburg', 'Morgantown', 'Wheeling', 'Martinsburg', 'Fairmont', 'Beckley', 'Clarksburg', 'Lewisburg', 'Buckhannon', 'Charles Town', 'South Charleston', 'St. Albans', 'Hurricane', 'Bridgeport', 'Ranson', 'Keyser', 'Point Pleasant', 'Weirton', 'Oak Hill', 'Elkins', 'Romney', 'New Martinsville', 'Shepherdstown'] },
      { code: 'WI', name: 'Wisconsin', cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton', 'Waukesha', 'Oshkosh', 'Eau Claire', 'Janesville', 'West Allis', 'La Crosse', 'Sheboygan', 'Wauwatosa', 'Fond du Lac', 'New Berlin', 'Wausau', 'Brookfield', 'Greenfield', 'Beloit', 'Franklin', 'Oak Creek', 'Manitowoc', 'West Bend', 'Sun Prairie', 'Superior', 'Neenah', 'Middleton', 'DeForest', 'Fitchburg'] },
      { code: 'WY', name: 'Wyoming', cities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs', 'Sheridan', 'Green River', 'Evanston', 'Riverton', 'Jackson', 'Cody', 'Rawlins', 'Lander', 'Torrington', 'Powell', 'Douglas', 'Worland', 'Buffalo', 'Wheatland', 'Newcastle', 'Thermopolis', 'Afton', 'Kemmerer', 'Saratoga', 'Pinedale'] }
    ]
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    states: [
      { code: 'DN', name: 'Distrito Nacional' },
      { code: 'AZ', name: 'Azua' },
      { code: 'BC', name: 'Baoruco' },
      { code: 'BH', name: 'Barahona' },
      { code: 'DJ', name: 'Dajabón' },
      { code: 'DU', name: 'Duarte' },
      { code: 'EL', name: 'Elías Piña' },
      { code: 'EP', name: 'Espaillat' },
      { code: 'HM', name: 'Hato Mayor' },
      { code: 'IN', name: 'Independencia' },
      { code: 'LR', name: 'La Romana' },
      { code: 'LV', name: 'La Vega' },
      { code: 'MR', name: 'María Trinidad Sánchez' },
      { code: 'MN', name: 'Monseñor Nouel' },
      { code: 'MC', name: 'Monte Cristi' },
      { code: 'MP', name: 'Monte Plata' },
      { code: 'NC', name: 'Nacional' },
      { code: 'PE', name: 'Pedernales' },
      { code: 'PN', name: 'Peravia' },
      { code: 'PP', name: 'Puerto Plata' },
      { code: 'SC', name: 'Salcedo' },
      { code: 'SM', name: 'Samaná' },
      { code: 'SN', name: 'San Cristóbal' },
      { code: 'SJ', name: 'San José de Ocoa' },
      { code: 'SJU', name: 'San Juan' },
      { code: 'SP', name: 'San Pedro de Macorís' },
      { code: 'SR', name: 'Sánchez Ramírez' },
      { code: 'SD', name: 'Santo Domingo' },
      { code: 'ST', name: 'Santiago' },
      { code: 'SR', name: 'Santiago Rodríguez' },
      { code: 'VA', name: 'Valverde' }
    ]
  },
  {
    code: 'ES',
    name: 'Spain',
    states: [
      { code: 'AN', name: 'Andalucía' },
      { code: 'AR', name: 'Aragón' },
      { code: 'AS', name: 'Asturias' },
      { code: 'IB', name: 'Islas Baleares' },
      { code: 'PV', name: 'País Vasco' },
      { code: 'CN', name: 'Canarias' },
      { code: 'CB', name: 'Cantabria' },
      { code: 'CM', name: 'Castilla-La Mancha' },
      { code: 'CL', name: 'Castilla y León' },
      { code: 'CT', name: 'Cataluña' },
      { code: 'EX', name: 'Extremadura' },
      { code: 'GA', name: 'Galicia' },
      { code: 'MD', name: 'Madrid' },
      { code: 'MC', name: 'Murcia' },
      { code: 'NC', name: 'Navarra' },
      { code: 'RI', name: 'La Rioja' },
      { code: 'VC', name: 'Comunidad Valenciana' }
    ]
  },
  {
    code: 'MX',
    name: 'Mexico',
    states: [
      { code: 'AGU', name: 'Aguascalientes' },
      { code: 'BCN', name: 'Baja California' },
      { code: 'BCS', name: 'Baja California Sur' },
      { code: 'CAM', name: 'Campeche' },
      { code: 'CHP', name: 'Chiapas' },
      { code: 'CHH', name: 'Chihuahua' },
      { code: 'COA', name: 'Coahuila' },
      { code: 'COL', name: 'Colima' },
      { code: 'DUR', name: 'Durango' },
      { code: 'GUA', name: 'Guanajuato' },
      { code: 'GRO', name: 'Guerrero' },
      { code: 'HID', name: 'Hidalgo' },
      { code: 'JAL', name: 'Jalisco' },
      { code: 'MEX', name: 'México' },
      { code: 'MIC', name: 'Michoacán' },
      { code: 'MOR', name: 'Morelos' },
      { code: 'NAY', name: 'Nayarit' },
      { code: 'NLE', name: 'Nuevo León' },
      { code: 'OAX', name: 'Oaxaca' },
      { code: 'PUE', name: 'Puebla' },
      { code: 'QUE', name: 'Querétaro' },
      { code: 'ROO', name: 'Quintana Roo' },
      { code: 'SLP', name: 'San Luis Potosí' },
      { code: 'SIN', name: 'Sinaloa' },
      { code: 'SON', name: 'Sonora' },
      { code: 'TAB', name: 'Tabasco' },
      { code: 'TAM', name: 'Tamaulipas' },
      { code: 'TLA', name: 'Tlaxcala' },
      { code: 'VER', name: 'Veracruz' },
      { code: 'YUC', name: 'Yucatán' },
      { code: 'ZAC', name: 'Zacatecas' },
      { code: 'DIF', name: 'Ciudad de México' }
    ]
  },
  {
    code: 'CA',
    name: 'Canada',
    states: [
      { code: 'AB', name: 'Alberta' },
      { code: 'BC', name: 'British Columbia' },
      { code: 'MB', name: 'Manitoba' },
      { code: 'NB', name: 'New Brunswick' },
      { code: 'NL', name: 'Newfoundland and Labrador' },
      { code: 'NS', name: 'Nova Scotia' },
      { code: 'ON', name: 'Ontario' },
      { code: 'PE', name: 'Prince Edward Island' },
      { code: 'QC', name: 'Quebec' },
      { code: 'SK', name: 'Saskatchewan' },
      { code: 'NT', name: 'Northwest Territories' },
      { code: 'NU', name: 'Nunavut' },
      { code: 'YT', name: 'Yukon' }
    ]
  },
  {
    code: 'BR',
    name: 'Brazil',
    states: [
      { code: 'AC', name: 'Acre' },
      { code: 'AL', name: 'Alagoas' },
      { code: 'AP', name: 'Amapá' },
      { code: 'AM', name: 'Amazonas' },
      { code: 'BA', name: 'Bahia' },
      { code: 'CE', name: 'Ceará' },
      { code: 'DF', name: 'Distrito Federal' },
      { code: 'ES', name: 'Espírito Santo' },
      { code: 'GO', name: 'Goiás' },
      { code: 'MA', name: 'Maranhão' },
      { code: 'MT', name: 'Mato Grosso' },
      { code: 'MS', name: 'Mato Grosso do Sul' },
      { code: 'MG', name: 'Minas Gerais' },
      { code: 'PA', name: 'Pará' },
      { code: 'PB', name: 'Paraíba' },
      { code: 'PR', name: 'Paraná' },
      { code: 'PE', name: 'Pernambuco' },
      { code: 'PI', name: 'Piauí' },
      { code: 'RJ', name: 'Rio de Janeiro' },
      { code: 'RN', name: 'Rio Grande do Norte' },
      { code: 'RS', name: 'Rio Grande do Sul' },
      { code: 'RO', name: 'Rondônia' },
      { code: 'RR', name: 'Roraima' },
      { code: 'SC', name: 'Santa Catarina' },
      { code: 'SP', name: 'São Paulo' },
      { code: 'SE', name: 'Sergipe' },
      { code: 'TO', name: 'Tocantins' }
    ]
  },
  {
    code: 'AR',
    name: 'Argentina',
    states: [
      { code: 'BA', name: 'Buenos Aires' },
      { code: 'CA', name: 'Catamarca' },
      { code: 'CH', name: 'Chaco' },
      { code: 'CT', name: 'Chubut' },
      { code: 'CB', name: 'Córdoba' },
      { code: 'CR', name: 'Corrientes' },
      { code: 'ER', name: 'Entre Ríos' },
      { code: 'FO', name: 'Formosa' },
      { code: 'JY', name: 'Jujuy' },
      { code: 'LP', name: 'La Pampa' },
      { code: 'LR', name: 'La Rioja' },
      { code: 'MZ', name: 'Mendoza' },
      { code: 'MI', name: 'Misiones' },
      { code: 'NQ', name: 'Neuquén' },
      { code: 'RN', name: 'Río Negro' },
      { code: 'SA', name: 'Salta' },
      { code: 'SJ', name: 'San Juan' },
      { code: 'SL', name: 'San Luis' },
      { code: 'SC', name: 'Santa Cruz' },
      { code: 'SF', name: 'Santa Fe' },
      { code: 'SE', name: 'Santiago del Estero' },
      { code: 'TF', name: 'Tierra del Fuego' },
      { code: 'TM', name: 'Tucumán' }
    ]
  }
]

// Ciudades principales por país
export const cities: Record<string, string[]> = {
  US: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
  DO: ['Santo Domingo', 'Santiago', 'San Pedro de Macorís', 'La Romana', 'San Francisco de Macorís', 'Puerto Plata', 'San Cristóbal', 'Higüey', 'Moca', 'Baní'],
  ES: ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'],
  MX: ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Torreón', 'Querétaro', 'San Luis Potosí'],
  CA: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener'],
  BR: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Goiânia'],
  AR: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Tucumán', 'La Plata', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan']
}